module.exports = {
  config: {
    frame: false,
    minimizable: false,
    maximizable: false,
    closable:false,
    titleBarStyle: 'customButtonsOnHover',
    updateChannel: 'stable',
    fontSize: 12,
    fontFamily: '"Victor Mono", Hack Nerd Font',
    fontWeight: 'normal',
    fontWeightBold: 'bold',
    lineHeight: 1,
    letterSpacing: 0,
    cursorColor: 'rgba(255,255,255,0.2)',
    cursorAccentColor: 'rgba(0,0,0,0)',
    cursorShape: 'BLOCK',
    cursorBlink: false,
    foregroundColor: '#fff',
    backgroundColor: '#000',
    selectionColor: '#bdae93',
    css: '',
    termCSS: '',
    padding: '1px',
    showHamburgerMenu: '',
    showWindowControls: '',
    colors: {
      black: '#000000',
      red: '#C51E14',
      green: '#1DC121',
      yellow: '#C7C329',
      blue: '#0A2FC4',
      magenta: '#C839C5',
      cyan: '#20C5C6',
      white: '#C7C7C7',
      lightBlack: '#686868',
      lightRed: '#FD6F6B',
      lightGreen: '#67F86F',
      lightYellow: '#FFFA72',
      lightBlue: '#6A76FB',
      lightMagenta: '#FD7CFC',
      lightCyan: '#68FDFE',
      lightWhite: '#FFFFFF',
    },
    shell: '',
    shellArgs: ['--login'],
    env: {},
    bell: 'SOUND',
    copyOnSelect: false,
    defaultSSHApp: true,
    quickEdit: false,
    macOptionSelectionMode: 'vertical',
    webGLRenderer: true,
    hyperBorder: {
      borderColors: ['black', 'black'],
      borderWidth: '2px',
    },
  },
  plugins: [
    "hyper",
    "hyperminimal",
    "hypercwd",
    "hyperborder",
    "hyper-gruvbox",
    "hyperemoji"
  ],
  localPlugins: [],
  keymaps: {},
}
